name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Unzip project
      run: unzip Why1000_Android_App.zip

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build APK
      run: |
        cd Why1000_Android_App
        chmod +x gradlew
        ./gradlew assembleDebug

    - name: Upload APK
      uses:  actions/upload-artifact@v4
      with:
        name: app-apk
        path: Why1000_Android_App/app/build/outputs/apk/debug/app-debug.apk
